name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name : set image version
      id: image_version
      run : echo "gitsha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: build docker
      run : docker build . --file Dockerfile --tag ghcr.io/obaidofj/express-docker:${{steps.image_version.outputs.gitsha}}
    - name : publish image
      run : docker push ghcr.io/obaidofj/express-docker:${{steps.image_version.outputs.gitsha}}
    - name: configure docker host
      uses: khaledez/configure-docker-host@v1
      with:
        host: 15.237.159.121
        user: github
        ssh-private-key: ${{secrets.DEPLOYMENT_KEY}}
    - name: deploy docker image
      run : docker compose -f docker-compose-prod.yml
      env:
        DB_PASSWORD: ${{secrets.DB_PASSWORD}}
    - name : print logs
      if: always()
      run : docker compose logs